### ISSUE TITLE
Detect client Id

### ISSUE THREAD

**Issue by nhdms** [rabbitmq/rabbitmq-event-exchange#30]
Hi, 
Can I detect which client just 'connected' or 'disconnected'
I tried consumerTag but It doesnot work @@
Thanks

**Comment by lukebakken** [comment]
Thank you for your time and for using RabbitMQ.

The RabbitMQ team uses GitHub issues for specific actionable items engineers can work on. This means that GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, and so on.

Please post your question or issue to the [`rabbitmq-users`](https://groups.google.com/forum/#!forum/rabbitmq-users) mailing list.

Thanks again!
Luke
