### ISSUE TITLE
Username on connection.closed?

### ISSUE THREAD

**Issue by johnfoldager** [rabbitmq/rabbitmq-event-exchange#4]
Would it be possible for you to add the username to connection.closed events in the same way as is the case for connection.created?

**Comment by dumbbell** [comment]
I looked at the code and, IMHO, it would require too much work for the small gain:

1. The place where this event is generated knows the connection details, but not the AMQP session (beside what it is known right from the beginning). So it would require some refactoring of the broker and the AMQP 1.0 plugin to communicate data such as the username up to the "connection closed" handling code.
2. With the current events, you can match the {{connection.created}} and the {{connection.closed}} using the PID and get back the information you seek.

**Comment by johnfoldager** [comment]
We already do that. However, if a request from a user comes in to delete all data about the user then we have one service that handles the event listening and another one handling the 'delete' call. If the delete call is handled first then all data is removed before the event listening task can get to the pid, so no details can be written to the log.
If the plugin was able to create an event with the username (as you say would in fact be possible, but a larger task) then we would have the information in the log as we need.

+1 to reopen this ;-)

**Comment by dumbbell** [comment]
Ok, I keep it open but it is low-priority.

**Comment by johnfoldager** [comment]
Thanks :o)

Thats fair enough since we already have a 99% working solution. Just hope that it will be considered when the different parts are updated later on.

**Comment by michaelklishin** [comment]
Low priority doesn't mean we will never do it but it may take months. Feel free to take a look into this on your own — we are happy to answer questions on our mailing list. This is open source software, after all ;)

**Comment by michaelklishin** [comment]
I will close this in favour of #10 which is the same idea but with broader scope (covers more event types).

**Comment by rept** [comment]
The ticket referred to is already merged but I fail to see how I can get the user_id from the connection.closed event?  Except of course through the pid and a DB lookup.

**Comment by lukebakken** [comment]
@rept - please post questions to the [`rabbitmq-users` mailing list](https://groups.google.com/forum/#!forum/rabbitmq-users) in the future, even if they apply to a GitHub issue or PR. The RabbitMQ team prefers to not use GitHub for discussions.

With regard to your question, the user id is not readily available when the `connection_closed` event is raised. What you can do, however, is use the "connection name" client property to store whatever information you like, and that information will be returned in the event details.

**Comment by rept** [comment]
@lukebakken Thx for your reply.
I have it working already with pid as was suggested earlier in this thread.  

Why I'm posting here is because I fail to see how this was closed (or a duplicate) because of #10 since #10 doesn't solve the need to save the pid (or connection name) on the connection create and later query it back in order to find the user for who the connection was closed.

No big thing, it's working but could be better, thanks for all the effort that went into this library!

**Comment by michaelklishin** [comment]
@rept my comment above  says

«which is the same idea but with broader scope (covers more event types)…»

We instead added acting user ID on most events where it was easy to do so. It is not for `connection.closed` for two reasons: 

 * A connection can be closed **before it is authenticated**, or exactly because it cannot be authenticated successfully. There would be no user  ID in that case (but there always is a pid).
  *  `rabbit_reader` implementation details do not make it easy to obtain full connection state, including the user ID, in certain failure scenarios.

I hope now you see.
